# Generated by Django 4.2 on 2023-06-29 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0002_movie_budget_movie_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollars"), ("RUB", "Rubles")],
                default="RUB",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.IntegerField(
                default=1000000,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
