# Generated by Django 4.2 on 2023-06-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0003_director_movie_currency_movie_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie_app.director",
            ),
        ),
    ]
