# Generated by Django 4.2 on 2023-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_bestseller",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
